# Site Settings
lang: en
title: Latimer
tagline: A general-purpose statically-typed interpreted language designed for efficiency, safety, and developer productivity.
email: jyoopyter.notebooks@gmail.com
description: >
  A general-purpose statically-typed interpreted language designed for efficiency, safety, and developer productivity.
baseurl: ""
url: "https://latimer-lang.org"
permalink: pretty
gh_link: joonyoo181/latimer
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: light

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true

markdown: kramdown
highlighter: rouge
